### ISSUE TITLE
PlanTypes

### ISSUE THREAD

**Issue by ghost** [sdpgroup7/code#104]
Define how the communication between CI and Planning is to work, and sort out the PlanTypes enum ordinal problem

**Comment by dephraser** [comment]
Chris, do you want to sit down sometime and just clairfy how we want to do
this?

On 8 March 2012 09:17, blasedef <
reply@reply.github.com

**Comment by ghost** [comment]
Yep,

Saturday?

**Comment by dephraser** [comment]
Sure

On 8 March 2012 10:07, blasedef <
reply@reply.github.com

**Comment by dephraser** [comment]
We never did get that done today, stuff still works without this change so
I would say put this off till after tomorrow.

David
