### ISSUE TITLE
overlay - can it take the new Astar information?

### ISSUE THREAD

**Issue by ghost** [sdpgroup7/code#112]
as above

**Comment by dalemyers** [comment]
Yes. I'll do that today if I can.

On Sun, 11 Mar 2012 10:47:09 -0000, blasedef  
reply@reply.github.com  
wrote:

> as above
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/sdpgroup7/code/issues/112

##

**Comment by jkhulme** [comment]
Seems to be working in strategy.  Can this issue be closed?

**Comment by dephraser** [comment]
Closing
