### ISSUE TITLE
Penalty Shoot mode

### ISSUE THREAD

**Issue by dephraser** [sdpgroup7/code#17]

**Comment by ghost** [comment]
has a planType just needs someone to take on the code

**Comment by ghost** [comment]
Penalty Offence:

1) Targeting system for the kick, we have a "clear_shot" function,
this should be improved and modified, it requires the ability to tell
if the opposition is in the way, and if there is another open shot if
the robot were to turn on the spot slightly. This can be re-used for
the general "kick" in Free_Play
