### ISSUE TITLE
Penalty Goalie mode

### ISSUE THREAD

**Issue by dephraser** [sdpgroup7/code#18]

**Comment by ghost** [comment]
has a planType, just needs someone to take on the code

**Comment by ghost** [comment]
Penalty Defence:

1) The robot turns/moves into the direction of the orientation of the
opposition
2) The robot plan is to drive into the intercept of the ball (I assume
we don't bother with a return to start position) - hence target needs
to be the intercept point @ they_have_ball == false

**Comment by ghost** [comment]
I'm unassigning you Dave, so that someone with more time can do this :)
