### ISSUE TITLE
A start sequence

### ISSUE THREAD

**Issue by dephraser** [sdpgroup7/code#22]
So that there is no delay when the start whistle goes

**Comment by dalemyers** [comment]
Right now we are also waiting 1 second because if we don't we start accessing null values from WorldState (or so I believe). This should be fixed with issue #55

**Comment by ghost** [comment]
Is this actually required?

**Comment by ghost** [comment]
..as in, don't we really quick move off the spot?

**Comment by dalemyers** [comment]
Doesn't seem to be required any more. Plans are calculated quickly. If anything all we would need is a start calculating button and a move button.

**Comment by ghost** [comment]
So make the robot start planning button, and then a let it off the leash button?

**Comment by dalemyers** [comment]
Pretty much. But I don't think its required. The alternative is when we initialise the planning stuff, create a new plan which is move x amount forward and send that immediately.

**Comment by ghost** [comment]
I am going to close this tomorrow if no one has any objections...

**Comment by ghost** [comment]
closed as per discussion.
