### ISSUE TITLE
RGB Normalisation fails on true black

### ISSUE THREAD

**Issue by dalemyers** [sdpgroup7/code#29]
If a pixel is true black with the values (0,0,0) then we are dividing by 0 which will cause everything to go wrong...

**Comment by Rado767** [comment]
We can have a check if the pixel values are all zero and just ignore that pixel in the normalisation. But will the camera ever produce such a pixel ? 

---

 From: Dale reply@reply.github.com
To: Rado767 rado_lxg@yahoo.com 
Sent: Wednesday, 25 January 2012, 23:44
Subject: [code] RGB Normalisation fails on true black (#29)

If a pixel is true black with the values (0,0,0) then we are dividing by 0 which will cause everything to go wrong...

---

Reply to this email directly or view it on GitHub:
https://github.com/sdpgroup7/code/issues/29

**Comment by dalemyers** [comment]
Yeah that's the plan, I just couldn't be bothered doing it tonight. As for the camera producing such a pixel, it's unlikely, but better safe than sorry.

**Comment by jkhulme** [comment]
Was my first version failing because It was doing integer division, so it was just setting red, green and blue to be 0*255?

**Comment by dalemyers** [comment]
Yeah pretty much.

**Comment by dalemyers** [comment]
Fixed.
