### ISSUE TITLE
Barrel Distortion

### ISSUE THREAD

**Issue by jkhulme** [sdpgroup7/code#31]
I'm going to try and get rid of the barrel distortion from the video feed.  This will mean more accurate distance calculation.  Dale how will this affect your code for isolating the pitch?

**Comment by dalemyers** [comment]
My code for isolating the pitch was started with the intention of removing this distortion in the most simple manner. I reckoned if we had each corner as well as where the biggest part of the bulges were then we could 'box' it up nicely. Does that make sense?

**Comment by jkhulme** [comment]
So, we have the corners, draw a line between the corners, and bring the bulges down onto their respective line?  That sort of idea?

**Comment by dalemyers** [comment]
Yeah that's what I was thinking. But if you can come up with a better way please feel free.

**Comment by jkhulme** [comment]
It sounds like it should work, I'd have to see an image that it outputted.  
http://mipav.cit.nih.gov/documentation/HTML%20Algorithms/BarrelDistortionCorrection.html I found this link which seems to be what we want.  I was also going to take a look at what the teams from last year did

**Comment by jkhulme** [comment]
Do you think that the bug with the points being slightly off is because of this distortion.  I'm not sure why that would be the case.

**Comment by dalemyers** [comment]
No I wouldn't think so. The co-ordinate comes from the panel, which the feed is simply projected onto. It shouldn't make any difference at all. I had a look at it but I couldn't see where it was going wrong.

**Comment by jkhulme** [comment]
I've looked through the previous years code and they seem to just have magic matrices.  Dale were you saying the one you posted to the mailing list just corrected points.  It might be easier, and take less processing time to just do that

**Comment by jkhulme** [comment]
Its currently working, just in the given area at a reasonable speed, but it is not clearing what is marked onto it.  Which is what needs worked on currently.

**Comment by jkhulme** [comment]
I think its working for just points, haven't been able to test it yet.  Possibly we will get array out of bounds exceptions.

**Comment by jkhulme** [comment]
Done
