### ISSUE TITLE
RGB Normalisation is slow

### ISSUE THREAD

**Issue by dalemyers** [sdpgroup7/code#32]
Using RGB Normalisation it brings the frame rate down to around 10fps. We will need to get it faster if we want to use it. KitB mentioned something in passing about HSV solving this for us? We should also test the speed of getting the bits from a color object vs binary shifting the values out.

**Comment by jkhulme** [comment]
We may not actually need to use rgb normalisation depending on how good javaCV is at the object recognition, and rado was saying he though that rgb would make the javacv stuff awkward

**Comment by dalemyers** [comment]
Played around with it a little bit to see if I could speed it up at all. The method we are currently using is the fastest.

**Comment by jkhulme** [comment]
not using normalisation - doesn't matter
