### ISSUE TITLE
Merge PC code into one src folder

### ISSUE THREAD

**Issue by ghost** [sdpgroup7/code#37]
To reduce the complexity of building and make it easier to import the project into IDEs, it would be good to put all code (except NXT) into one folder. This could be done after Milestone 1 or once the Vision code is stabilised. We would have just 3 ant build files: 1 for the whole PC code, 1 for NXT and 1 root/central (with something like 'ant robot' task which would build and upload/run the NXT code by calling the build file in the NXT folder, and 'ant pc' or just default that would build the one in the folder for all code to be run on PC).

**Comment by dephraser** [comment]
Yeah, but definitely something to do after the milestone.

On 30 January 2012 08:20, ttauber <
reply@reply.github.com

**Comment by ghost** [comment]
done
