### ISSUE TITLE
Use SwingWorker to run recognition code on demand

### ISSUE THREAD

**Issue by dalemyers** [sdpgroup7/code#38]
Use SwingWorker so that we can click the "Locate Objects" button and reset the data about the objects.

**Comment by jkhulme** [comment]
So Use the run in background bit of it so that the video feed will still run?

**Comment by dalemyers** [comment]
Pass. I haven't had a chance to look over it fully yet, and I
certainly can't remember what I did read.

On 31 Jan 2012, at 10:57, James Hulme
reply@reply.github.com
wrote:
