### ISSUE TITLE
Simulator Instructions Required

### ISSUE THREAD

**Issue by dalemyers** [sdpgroup7/code#56]
We need instructions in order to be able to use the simulator. Right now no one knows how to use it, or indeed can even understand it.

**Comment by jkhulme** [comment]
Instructions exist now on how to run

**Comment by dalemyers** [comment]
They have for a while, but do they work?
On Mar 20, 2012 2:50 PM, "James Hulme" <
reply@reply.github.com>
wrote:

**Comment by jkhulme** [comment]
I figured this applied most to instructions on how to actually start the simulator, hopefully once we got that far it would just be press start match
