### ISSUE TITLE
Pitch 2 Constants

### ISSUE THREAD

**Issue by dalemyers** [sdpgroup7/code#59]
These should be measured and put into worldstate. This includes colour, corners and buffers.

**Comment by jkhulme** [comment]
Could probably include the zoning of the second pitch into this as well

**Comment by Rado767** [comment]
Will do

**Comment by Rado767** [comment]
I have almost finished now. I need the robot to test with it. Dale I wrote the new constants, but they are never updated after the program is started. So when we push the button and the new constants are in place the lines are not redrawn.

**Comment by jkhulme** [comment]
Done
