### ISSUE TITLE
Robot no longer responds at all to bump sensors

### ISSUE THREAD

**Issue by dephraser** [sdpgroup7/code#63]
Robot will no longer respond at all to the bump sensors being pressed

**Comment by ghost** [comment]
Can you be more specific? (and are there connected to the right sensor ports?) Yesterday as you could see, I couldn't reconstruct this in a simple code that captured only the Control part of the system (i.e. it wasn't dependant on other parts of the system) - it went in an infinite loop forward (one command was sent every second) and any time I pressed bump sensors, it reacted. So, I suspect it might not respond it if it's overflown by commands (especially by arcs that might be more long running in LeJOS, as they require greater coordination of motors) - I could code some filtering in control, but this would make the code more complex + may cause other problems that it wouldn't react immediately or the way you want it... Today, I'm not available until 9pm or so, so please try to resolve it yourself (e.g. by sending less commands and having a pause if you want to send more than one at a time).

**Comment by dephraser** [comment]
The sensors are connected on ports one and two which I don't think has
changed.

The problem still persists even when given a direct drive command from the
UI, not through planning and strategy.

Is the code in develop the current code running on the brick? I see the
code has been changed with regard to the reaction with a new command in the
pilot 'quickStop()'. I'll have a fiddle in there and see if that is the
cause.

Note: This is not the infinite loop problem, this is a new problem. Before
the sensors reacted then went into the loop. Here they are just not
reacting at all.

On 28 February 2012 11:20, ttauber <
reply@reply.github.com

**Comment by ghost** [comment]
It should be, but apologies if it isn't or if the quickStop messes it up (due to tired Tom being less cautious or due lejos brick not rewriting the old codes) - anyway just for sure, before uploading the code onto the brick, delete the existing code on the brick (Nxt_code.nxj, plus there might be odometry.nxj which is out-dated experimental Nxt_code).
As said on IRC, feel free to change it.

**Comment by jkhulme** [comment]
I believe this was fixed
