### ISSUE TITLE
PlanTypes :: action=TURN, Send CI turn on spot

### ISSUE THREAD

**Issue by ghost** [sdpgroup7/code#70]
What happens if A\* does not need to make a path at all?
We need to be able to ask CI just to x to an orientation...

**Comment by ghost** [comment]
David I just assigned this to you to draw your attention to it. Is it right that turn on the spot should be different from drive? My thoughts are that turning on the spot does not require a path..?

**Comment by dephraser** [comment]
Yeah, turning on the spot wont require a path but it will require
a separate action type

On 28 February 2012 12:57, blasedef <
reply@reply.github.com

**Comment by dephraser** [comment]
Also now I think about it (obvious really >.<) Ill need an angle to turn by
or a direction to point.

David
