### ISSUE TITLE
VisionTools Testing

### ISSUE THREAD

**Issue by dalemyers** [sdpgroup7/code#79]
We need to confirm that all methods in vision tools return the correct data. Can someone have a look and make sure these work correctly.

**Comment by jkhulme** [comment]
I'm going to work on the vision testing framework in the next couple of days.  I can put tests for the vision tools stuff in with that

**Comment by dalemyers** [comment]
Awesome. Thanks.

**Comment by jkhulme** [comment]
Its in the testing now, it's not JUnit.
