### ISSUE TITLE
Flexible PlanTypes

### ISSUE THREAD

**Issue by dalemyers** [sdpgroup7/code#80]
We need to have just a defence mode. That way we can use it when we are goalie for a penalty or whenever we lose the ball (e.g. the opponent has the ball) we should run home and defend. The only other time we would lose the ball is when someone scores. All that happens then is that we go back to the goals, which is what we want.

**Comment by lauriepicken** [comment]
I'm not sure about this man, I think it should be called something more like GoalLine Defence. Defence should be a higher level mode that encompasses this and other strategies, rather than just running back to our goal all the time.

**Comment by dalemyers** [comment]
Yeah I think that makes more sense.

**Comment by ghost** [comment]
Although, we still don't want to lose the idea of being able to go from FREEPLAY into DEF...

**Comment by dalemyers** [comment]
Why would this make us lose it?

**Comment by ghost** [comment]
Laurie answered with a difference in name change. The overall point is the on the fly defence play, I personally don't care what it is called, don't resolve this issue :: don't lose the idea. :)

**Comment by ghost** [comment]
Sorry, I overrode to make more pertinent:

It would be good if we can go into penalty mode (def) on the fly, hence both types need to be able to break out into each other.
