### ISSUE TITLE
In Defence mode move to the point the opponent is facing

### ISSUE THREAD

**Issue by dalemyers** [sdpgroup7/code#81]
If we are in defence mode then we should be in the position along the goal line which the opponent is facing (e.g. where they are going to shoot).

**Comment by lauriepicken** [comment]
This will be fine for penalty defence but not for overall defence. If we can get into their shooting line earlier we should do that instead, avoiding unnecessary driving back to the goal.

**Comment by dalemyers** [comment]
Again I agree. I really need to think before I wrote...
