### ISSUE TITLE
Specify goal line in world state

### ISSUE THREAD

**Issue by dalemyers** [sdpgroup7/code#82]
As above.

**Comment by ghost** [comment]
And put it so our robot can sit on it :)

**Comment by jkhulme** [comment]
Is the goal line not specified in WorldState.updateShootingDirection()?

**Comment by ghost** [comment]
Specifically the list of Points, that is just infront and between the goal
posts.
On Mar 9, 2012 11:52 AM, "James Hulme" <
reply@reply.github.com>
wrote:

**Comment by ghost** [comment]
err to elaborate, it would be useful to use in penalty defence / free play
defence, it means we can find the position to sit (and also gives us a line
to shoot to...)

**Comment by ghost** [comment]
I think we have got this covered... Laurie?
