### ISSUE TITLE
Angles

### ISSUE THREAD

**Issue by ghost** [sdpgroup7/code#83]
Need to go through the code, and ensure that all angles work in:

AllMovingObjects
AllStaticObjects
TargetDecision
Plan

If it is no big deal, convert all angles into Planning angles in AllMovingObjects/AllStaticObjects and then convert back when passing to CI

**Comment by dalemyers** [comment]
I thought that planning used the same angle system as the vision system?

**Comment by ghost** [comment]
I thought I read the vision system is going for that 0 is up thing? Which is not what planning would naturally use.

That was in the last email I read about it -- 

In either case, which ever way round it is, someone still needs to check that the planning system is using the correct angles

**Comment by dalemyers** [comment]
Yeah that's what vision uses, but its easy to convert visions stuff (we have to change a single method).

**Comment by ghost** [comment]
I just read the email again.

The Vision system is remaining with the 0 is up

When working in nodes, IE get the angle between the node at the centre of the goal to the node ball, it is in the 'normal' angle system, 0 is to the right.

To deal with this, all Vision system angles are going to need to be converted, and this should happen in AllMovingObjects and AllStaticObjects, and thus all angles in the Planning system need to be checked that:

A) they only get their angles through a conversion function AllMovingObjects or AllStaticObjects class
B) there are no angles being taken directly from the vision system anywhere else in the Planning code

If the above doesn't happen, we are going to have a harder time debugging.

If it needs to go back the other way when it enters CI we can just re-apply the angle conversion again.

VISION(0 up) -> PLANNING(0 right) -> CI(0 up)

I'm not going to convert the node angles everytime I want to use them, it doesn't make any sense. It is easier just to convert them back to normal inside the planning code.

**Comment by jkhulme** [comment]
I believe this issue is sorted
