### ISSUE TITLE
A*

### ISSUE THREAD

**Issue by ghost** [sdpgroup7/code#86]
1) Needs to not use just binary obstacles
2) Needs to include weighting for turning
3) Needs to not be so damn fragile

**Comment by lauriepicken** [comment]
How's it going with this man?
If you're gonna be around tomorrow night it would be sound if you could go through what you've done with me.
Don't worry if not, I'll just have a look at the alterations to the code.
Thanks

**Comment by ghost** [comment]
Hi Laurie,

I did a whole load on Sunday night, I had to throw out a whole lot of the old code because it didn't make sense with costing. I was working with Dale on it yesterday morning, it is nearly there basically. Should be up by Saturday hopefully....

**Comment by ghost** [comment]
complete
