### ISSUE TITLE
Simulator + MainRunner

### ISSUE THREAD

**Issue by dephraser** [sdpgroup7/code#88]
Looking in the code for MainRunner there seems to be a structure already there to fire up the simulator instead of vision. 

Is the intention to move Simulator.java over into there at some point. There seems to be no provision for the the gui or strategy system in Simulator.java.

Is this still work in progress or can I go ahead and merge the two together?

**Comment by wikkyk** [comment]
What exactly do you mean?

**Comment by dalemyers** [comment]
In case you start working on this, I have started on a branch called
control. So far all I have done is stripped out the crap from RobotControl
which isn't needed, and made it wait for a response.

Dale
