### ISSUE TITLE
worldstate singleton

### ISSUE THREAD

**Issue by jkhulme** [sdpgroup7/code#90]
Is worldstate a singleton yet?

**Comment by dalemyers** [comment]
Yes. All systems except vision use it this way. I just never quite got
round to sorting vision...
On Mar 7, 2012 10:16 AM, "James Hulme" <
reply@reply.github.com>
wrote:

**Comment by dephraser** [comment]
Can this issue be closed then or does work still need to be done?

**Comment by dalemyers** [comment]
Vision still needs to do it.

On Thu, 08 Mar 2012 12:48:43 -0000, David Fraser  
reply@reply.github.com  
wrote:

> Can this issue be closed then or does work still need to be done?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/sdpgroup7/code/issues/90#issuecomment-4390605

##

**Comment by jkhulme** [comment]
Do we need to make all the things like pitch be singletons as well?  Or is it ok because we only access them via WorldState

**Comment by jkhulme** [comment]
Also in Vision.java it has worldState = WorldState.getInstance();
Isn't this what is required for vision to be using a singleton?

**Comment by jkhulme** [comment]
Clarification: We need to go through the vision code and remove reference to Vision.WorldState.foobar() and replace with the singleton version

**Comment by jkhulme** [comment]
I believe dale fixed this
