### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by ghost** [sdpgroup7/code#93]
Better handling of threads -- https://github.com/sdpgroup7/code/issues/109
Runflag for all staticobjects (move/remove) -- https://github.com/sdpgroup7/code/issues/108
Path visualization from String[][](change to char[][] at least)
Potential uncaught exceptions that can cause a thread to die
etc.

**Comment by dalemyers** [comment]
I've removed the Node extends Points thing as that is in place in a different branch and will be merged shortly.

**Comment by ghost** [comment]
ok np

**Comment by ghost** [comment]
Why does the runFlag need to be moved?

**Comment by ghost** [comment]
Plus can you drop the enums from here, I'll make an issue that covers these

**Comment by ghost** [comment]
"Better handling of threads" could you elaborate?

**Comment by ghost** [comment]
Done.

Ad runFlag: because staticobjects don't implement runnable nor extend a thread, so in this way it makes things more confusing and can cause potential problems both with any changes in the code and running it, for example if you lose/rewrite the reference to staticobjects. If this is a standard practice, please point me at a source (tutorial/API) where the "logic" behind this thread management comes from. Cheers

**Comment by ghost** [comment]
"better handling of threads": https://groups.google.com/d/msg/sdpgroup7/KmUHqDzhwTw/YMZYsqa06FwJ

**Comment by ghost** [comment]
i.e. a cleaner thread execution/create management, cautious operations (atomic/synchronized..) with shared resources and so on

**Comment by ghost** [comment]
@ runFlag - There is no API or logic for this, it works, it is simple :P - otherwise in this case a new object/interface would need to be created just fo runFlag unless I...

@ Threads - ..change the whole way the Threading works. I have said before, I don't understand how I would implement this  / I don't have time to learn how to use threads in the manner you are suggesting.

Bottom line (I don't mean to sound rude!) : I am not changing either of these, they work.

**Comment by ghost** [comment]
having said that ^^^ I would be happy for you to show me how to do this, and I mean literally we both sit down and go through how that could work... I am not adverse to working on it, I am adverse to doing it on my own.

**Comment by threads** [comment]
think that one went to the wrong dude :)

## 

Kind regards
Klaus L. Hougesen
Creative Director, Threads

mobile: +45 2119 5912
skype: klaushougesen
www.threads.dk | www.bythreads.com

**Comment by klh** [comment]
what me why? :)

**Comment by ghost** [comment]
-- Oops sorry "Threads" I wondered why that went all bold in the text:: didn't know that could happen, slightly embarrassing...

**Comment by ghost** [comment]
Tom I have split out both of those issues so that this doesn't get too messy....

**Comment by ghost** [comment]
"works" = the robot failed both friendly matches; it is very hard / impossible to track what when goes wrong; no unit tests or anything measurable that see how (well) it works

runFlags are usually in threads they control. If you write down an execution flow from when you hit start to when you hit end in the context of all asynchronous ops and shared resources with references to relevant existing objects, I can sit down and go through it. Similarly, as you don't have time to read tutorials/APIs, I don't have time to go through a complex code that could' ve been clearer and more reliable if it followed standard practices described everywhere

**Comment by ghost** [comment]
1) "works" = the runFlag works. It starts and stops the Thread. 

2) "I don't have time to go through a complex code that could' ve been clearer and more reliable if it followed standard practices described everywhere". What would be useful, is if you actually showed me how to do this, rather than covertly said what I have done is shit, its really not good for the morale old chap. You know how it is meant to be done, I know how the system works - show me how to do this correctly.

**Comment by ghost** [comment]
I apologise if that offended you, I didn't mean it personally - and I didn't say "what you have done is shit" - all I'm saying is "look, here are some problems, here are some potential problems and here are a bit obscure things that could potentially lead to problems later on".

**Comment by ghost** [comment]
I don't know every single detail of relevant concurrent API off the top of my head and I've already outlined some relevant bits in GG. If you kindly provided me with a brief execution flow (I know the basics, but you mentioned there were some "one-off" threads fired off somewhere etc.), I could start thinking what fits best and then show you.

**Comment by ghost** [comment]
Ah wires crossed, probably being an English boy and over reading polite, anyway:

Absolutely can do that, its only one thread now, just PlanningThread, but also David's CI needs to be factored into "fixing threads" as you mentioned his code being kicked off by an update. When is most suitable for you?

Cheers by the way dude, its appreciated.

**Comment by ghost** [comment]
No worries, I'm in tomorrow, mostly working on the control code changes for Sunday match, but feel free to ask if you're stuck with anything.
CI may be actually safe after the control changes - command sending will be locked until a response is received (event. some timeout), i.e. the update/notifyObservers will be pause there.

The main change in this sense is to remove that while loop and have just if statement there - just one boolean as a private member of that runnable object; and wherever this is started, it'll be created only once and then use the thread scheduler facility to get it running (the advantages are, for example, that it reuses existing threads rather than creating new ones, it hints Java the task should be periodically executed, so JVM will try to do so and prevents starving from heavy demanding threads elsewhere, and if some uncaught exception kills the thread, it will recover from it as soon as it's rescheduled)
